import { randomUUID } from 'node:crypto';
import { afterAll, beforeAll, expect, test } from 'vitest';
import { createDb } from '@ekyc/shared/db';
import { Calls } from '../../ekyc-vidcall-backend/src/calls.js';
import { Jibri } from '../../ekyc-vidcall-backend/src/jibri.js';
import { Customers } from '../../ekyc-backend-master/src/customers.js';

const testUrl = process.env.TEST_DATABASE_URL;
if (!testUrl || !new URL(testUrl).pathname.endsWith('_test') || process.env.NODE_ENV === 'production') throw new Error('Integration tests require an isolated *_test PostgreSQL database and nonproduction mode');
const db = createDb(testUrl);
const tenant = randomUUID(); const customer = randomUUID(); const agent = randomUUID(); const otherAgent = randomUUID();
const cfg = { jitsiAppId: 'ekyc', jitsiDomain: 'meet.localhost', jitsiSecret: 'test-secret-that-has-at-least-32-characters', recordingBucket: 'test', reconnectGrace: 60, recordingTimeout: 90 };
const calls = new Calls(db, cfg, { checksum: async () => ({ sha256: 'a'.repeat(64), bytes: 200_000 }) });
const customers = new Customers(db, { cfg: { encryptionMock: true }, transform: async (_action, _tenant, data) => data });
const actor = { sub: agent, tenant_id: tenant, role: 'agent', sid: randomUUID() };
const client = { sub: customer, tenant_id: tenant, role: 'customer', sid: randomUUID() };
beforeAll(async () => {
  await db('platform_tenants').insert({ id: tenant, name: 'Integration test' });
  await db('platform_customers').insert({ id: customer, tenant_id: tenant, data: { name: 'Synthetic' }, encryption_format: 'synthetic-plaintext' });
  await db('platform_agents').insert([{ id: agent, tenant_id: tenant, username: `test-${agent}`, name: 'Agent A', password_hash: 'unused' }, { id: otherAgent, tenant_id: tenant, username: `test-${otherAgent}`, name: 'Agent B', password_hash: 'unused' }]);
  await db('platform_quotas').insert({ tenant_id: tenant, service: 'videocalls.post', remaining: 10 });
});
afterAll(async () => {
  const ids = (await db('platform_calls').where({ tenant_id: tenant }).select('id')).map(row => row.id);
  await db('platform_sessions').where({ tenant_id: tenant }).del();
  await db('platform_outbox').del();
  await db('platform_audit').where({ tenant_id: tenant }).del();
  await db('platform_events').del();
  await db('platform_decisions').where({ tenant_id: tenant }).del();
  await db('platform_recording_slots').whereIn('recording_id', db('platform_recordings').select('id').whereIn('call_id', ids)).update({ recording_id: null });
  await db('platform_recordings').whereIn('call_id', ids).del();
  await db('platform_calls').where({ tenant_id: tenant }).del();
  await db('platform_quotas').where({ tenant_id: tenant }).del();
  await db('platform_agents').where({ tenant_id: tenant }).del();
  await db('platform_customers').where({ tenant_id: tenant }).del();
  await db('platform_tenants').where({ id: tenant }).del();
  await db.destroy();
});

test('mandatory recording gates admission and idempotent completion', async () => {
  const key = randomUUID();
  const call = await calls.register({ tenant_id: tenant }, { user_id: customer }, key);
  const queueEvent = await db('platform_outbox').where({ dedupe_key: `${call.id}:${call.version}:queue.change` }).first();
  expect(queueEvent.payload.data.call).toMatchObject({ id: call.id, state: 'waiting', user_id: customer });
  expect((await calls.register({ tenant_id: tenant }, { user_id: customer }, key)).id).toBe(call.id);
  const assigned = await calls.claim(actor);
  expect(assigned.state).toBe('assigned');
  await expect(calls.claim({ ...actor, sub: otherAgent })).rejects.toMatchObject({ code: 'QUEUE_EMPTY' });
  await calls.consent(call.id, client, 'v1');
  const agentAdmission = await calls.admission(call.id, actor, 'Synthetic Customer');
  expect(agentAdmission.room).toMatch(/^verifikasi-synthetic-customer-[a-f0-9]{8}$/);
  const room = agentAdmission.room;
  const recording = await db('platform_recordings').where({ call_id: call.id }).first();
  const objectKey = `${tenant}/${customer}/${call.id}/${recording.id}.mp4`;
  await expect(calls.recordingEvent({ event_id: randomUUID(), call_id: call.id, recording_id: recording.id, worker_id: recording.worker_id, status: 'started' })).rejects.toMatchObject({ code: 'UNEXPECTED_RECORDING_START' });
  await expect(calls.admission(call.id, client)).rejects.toMatchObject({ code: 'RECORDING_NOT_RESERVED' });
  await calls.participantJoined(actor, room);
  expect((await db('platform_calls').where({ id: call.id }).first()).state).toBe('ringing');
  await expect(calls.admission(call.id, client)).resolves.toBeTruthy();
  await calls.participantJoined(client, room);
  expect((await db('platform_calls').where({ id: call.id }).first()).customer_joined_at).toBeTruthy();
  expect((await db('platform_outbox').where({ topic: 'recording.start', dedupe_key: `${call.id}:record` }).first())).toBeTruthy();
  await calls.recordingEvent({ event_id: randomUUID(), call_id: call.id, recording_id: recording.id, worker_id: recording.worker_id, status: 'started' });
  expect((await calls.admission(call.id, client)).room).toBe(room);
  expect((await db('platform_calls').where({ id: call.id }).first()).state).toBe('active');
  await calls.decide(call.id, actor, { outcome: 'verified' });
  await calls.recordingEvent({ event_id: randomUUID(), call_id: call.id, recording_id: recording.id, worker_id: recording.worker_id, status: 'stopped' });
  await expect(customers.applyDecision({ call_id: call.id, tenant_id: tenant, user_id: customer, outcome: 'verified' })).rejects.toMatchObject({ code: 'RECORDING_NOT_STORED' });
  calls.storage.checksum = async () => ({ sha256: 'a'.repeat(64), bytes: 48 });
  await expect(calls.stored({ event_id: randomUUID(), recording_id: recording.id, key: objectKey, sha256: 'a'.repeat(64), bytes: 48 })).rejects.toMatchObject({ code: 'RECORDING_INCOMPLETE' });
  calls.storage.checksum = async () => ({ sha256: 'a'.repeat(64), bytes: 200_000 });
  await expect(calls.stored({ event_id: randomUUID(), recording_id: recording.id, key: objectKey, sha256: 'a'.repeat(64), bytes: 200_000 })).resolves.toBeTruthy();
  const payload = { call_id: call.id, tenant_id: tenant, user_id: customer, outcome: 'verified' };
  await customers.applyDecision(payload); await customers.applyDecision(payload);
  expect((await calls.complete(payload)).state).toBe('completed');
  expect((await calls.complete(payload)).state).toBe('completed');
  expect((await db('platform_customers').where({ id: customer }).first()).verification_status).toBe('verified');
});
test('competing agents cannot claim one queue item and a recorder failure blocks verification', async () => {
  const nextCustomer = randomUUID();
  await db('platform_customers').insert({ id: nextCustomer, tenant_id: tenant, data: { name: 'Synthetic two' }, encryption_format: 'synthetic-plaintext' });
  const waiting = await calls.register({ tenant_id: tenant }, { user_id: nextCustomer }, randomUUID());
  const nextClient = { ...client, sub: nextCustomer };
  await calls.consent(waiting.id, nextClient, 'v1');
  const results = await Promise.allSettled([calls.claim(actor), calls.claim({ ...actor, sub: otherAgent })]);
  expect(results.filter(x => x.status === 'fulfilled')).toHaveLength(1);
  const winner = results.find(x => x.status === 'fulfilled').value;
  expect(winner.id).toBe(waiting.id);
  const winnerActor = { ...actor, sub: winner.agent_id };
  const winnerAdmission = await calls.admission(waiting.id, winnerActor, 'Synthetic two');
  await calls.participantJoined(winnerActor, winnerAdmission.room);
  await calls.participantJoined(nextClient, winnerAdmission.room);
  const recording = await db('platform_recordings').where({ call_id: waiting.id }).first();
  await calls.recordingEvent({ event_id: randomUUID(), call_id: waiting.id, recording_id: recording.id, worker_id: recording.worker_id, status: 'started' });
  await calls.recordingEvent({ event_id: randomUUID(), call_id: waiting.id, recording_id: recording.id, worker_id: recording.worker_id, status: 'failed' });
  expect((await db('platform_calls').where({ id: waiting.id }).first()).state).toBe('failed');
  expect((await db('platform_recording_slots').where({ recording_id: recording.id }).first())).toBeTruthy();
  const jibri = new Jibri(db, cfg, calls);
  jibri.request = async () => ({ status: { busyStatus: 'IDLE', health: { healthStatus: 'HEALTHY' } } });
  await jibri.poll();
  expect((await db('platform_recording_slots').where({ recording_id: recording.id }).first())).toBeUndefined();
  await expect(calls.decide(waiting.id, winnerActor, { outcome: 'verified' })).rejects.toMatchObject({ code: 'CALL_NOT_ACTIVE' });
  await expect(calls.get(waiting.id, { role: 'customer', tenant_id: tenant, sub: customer })).rejects.toMatchObject({ code: 'CALL_NOT_FOUND' });
});
