import { readdir, readFile, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
const roots = ['../infinid-agent-frontend', '../infinid-backend-new', '../infinid-vidcall-backend'];
const ignored = new Set(['node_modules', '.git', 'build', 'dist', 'coverage', 'vendor']);
async function files(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (ignored.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...await files(full));
    else if (/\.(js|jsx|mjs|cjs)$/.test(entry.name)) out.push(full);
  }
  return out;
}
function unique(values) { return [...new Set(values)].sort(); }
const lines = [
  '# Legacy JavaScript module and function inventory', '',
  'Generated by `npm run inventory`. This is a static source index, not proof of runtime behavior. Parameter and credential values are intentionally excluded.', '',
  'Replacement ownership: UI and browser events → `ekyc-agent-frontend`; customer, document, provider, OTP and tenant work → `ekyc-backend-master`; queue, session, call, socket and recording work → `ekyc-vidcall-backend`. Placeholder routes require explicit unavailable responses until implemented.', '',
];
for (const root of roots) {
  const list = await files(root);
  lines.push(`## ${path.basename(root)} (${list.length} JavaScript files)`, '');
  for (const file of list) {
    const source = await readFile(file, 'utf8');
    const names = unique([
      ...[...source.matchAll(/\b(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*\(/g)].map(match => match[1]),
      ...[...source.matchAll(/\b(?:class)\s+([A-Za-z_$][\w$]*)\b/g)].map(match => match[1]),
      ...[...source.matchAll(/\b(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*(?:async\s*)?(?:\([^)]*\)|[A-Za-z_$][\w$]*)\s*=>/g)].map(match => match[1]),
      ...[...source.matchAll(/(?:^|\n)\s*(?:async\s+)?([A-Za-z_$][\w$]*)\s*\([^\n{}]*\)\s*\{/g)].map(match => match[1]),
    ]);
    const routes = unique([...source.matchAll(/\b(?:app|router|route)\.(?:get|post|put|patch|delete)\s*\(\s*['"`]([^'"`]+)['"`]/g)].map(match => match[1]));
    const events = unique([...source.matchAll(/\.(?:emit|on)\s*\(\s*['"`]([^'"`]+)['"`]/g)].map(match => match[1]));
    const relative = path.relative('..', file).replaceAll('\\', '/');
    lines.push(`- \`${relative}\` — ${names.length ? `functions/classes: ${names.map(x => `\`${x}\``).join(', ')}` : 'no named declarations detected'}${routes.length ? `; routes: ${routes.map(x => `\`${x}\``).join(', ')}` : ''}${events.length ? `; events: ${events.map(x => `\`${x}\``).join(', ')}` : ''}`);
  }
  lines.push('');
}
await mkdir('docs', { recursive: true });
await writeFile('docs/legacy-inventory.md', lines.join('\n'));
console.log(`Indexed ${roots.length} source repositories into docs/legacy-inventory.md`);
